### PR TITLE
Align the layout with Markdown standards

### PR DESCRIPTION
**Pull request by oleg-nenashev**
No content changes, just header levels and one list spacing

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Review by martinbonnin — APPROVED** [review]

**Comment by martinbonnin** [comment]
Out of curiosity, is that our own standard or are there guideline around this?

**Comment by oleg-nenashev** [comment]
There are multiple ones. I usually use GitHub Flavoured Markdown:
https://github.github.com/gfm . Some implementations, including Material
for MkDocs, use another renderer, and there re some behavioral differences.
But even GFM is quite extensive on how to do lists, though in fact GitHub
is more permissive

**Comment by martinbonnin** [comment]
But this PR replaces h1 with h2, h2 with h3, etc... Is that something expected in READMEs? Or something we should do moving forward for inclusion in mkdocs?

**Comment by oleg-nenashev** [comment]
Normally in markdown the first level becomes a title (h1 in the layouts)
and the next levels align accordingly. Most markdown engines are robust
against different configurations, but I aligned it with normal style while
around

**Pull request merged**
